home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.index, name='index'),
	path('admin/', views.admin, name='admin'),
	path('players/', views.players, name='players'),
	path('team/', views.team, name='team'),
	path('scores/', views.scores, name='scores'),
	path('leaderboard/', views.leaderboard, name='leaderboard'),
	path('rules/', views.rules, name='rules'),
]

iitpl_fantasy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('home.urls')),
    path('players/', include('players.urls')),
    path('team/', include('team.urls')),
    path('scores/', include('scores.urls')),
    path('leaderboard/', include('leaderboard.urls')),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
	path('', views.playerList, name='player_list'),
	path('create/', views.createPlayer, name='player_create'),
	path('add/', views.addPlayer, name='addPlayer'),
	path('delete/<pk>/', views.PlayerDelete.as_view(), name='player_delete'),
	path('<pk>/', views.PlayerDetail.as_view(), name='player_detail'),
]

players/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
	name = models.CharField(max_length=20, primary_key=True)
	ssn = models.CharField(max_length=20, blank=True)
	squad = models.CharField(max_length=20, blank=True)
	category = models.CharField(max_length=15, blank=True)
	venom = models.IntegerField(default=0)
	fresher_pg = models.CharField(max_length=10, blank=True)

	def __str__(self):
		return self.name

class PlayerStats(models.Model):
	player = models.OneToOneField(Player, on_delete=models.CASCADE)
	runs = models.IntegerField(default=0)
	matches = models.IntegerField(default=0)
	highest_run = models.IntegerField(default=0)
	balls = models.IntegerField(default=0)
	wickets = models.IntegerField(default=0)
	run_conceded = models.IntegerField(default=0)
	highest_wicket = models.IntegerField(default=0)

	def __str__(self):
		return self.player.name

players/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import Player
import pandas as pd

# Create your views here.
def playerList(request):
	musketeers = Player.objects.filter(squad='Musketeers').order_by('venom').reverse()
	redhawks = Player.objects.filter(squad='Redhawks').order_by('venom').reverse()
	spartans = Player.objects.filter(squad='Spartans').order_by('venom').reverse()
	thunder = Player.objects.filter(squad='Thunder Strikers').order_by('venom').reverse()
	context = {'musketeers' : musketeers, 'redhawks' : redhawks,
		'spartans' : spartans, 'thunder' : thunder}
	return render(request, 'players/player_list.html', context)

class PlayerDetail(generic.DetailView):
	model = Player
	template_name = 'players/player_detail.html'

def createPlayer(request):
	categories = ['Batsman', 'Bowler', 'All-Rounder', 'Wicket-Keeper']
	venoms = [25, 50, 100, 150, 200]
	freshers = ['Fresher', 'PG', 'None']
	squads = ['Spartans', 'Musketeers', 'Redhawks', 'Thunder Strikers']
	context = {'categories' : categories, 'venoms' : venoms, 'freshers' : freshers, 'squads' : squads}
	return render(request, 'players/player_create.html', context)

def addPlayer(request):
	name = request.POST['name']
	ssn = request.POST['ssn']
	squad = request.POST['squad']
	venom = int(request.POST['venom'])
	category = request.POST['category']
	freshers = request.POST['freshers']
	p = Player(name=name, ssn=ssn, squad=squad, venom=venom, category=category, fresher_pg=freshers)
	p.save()
	return redirect('/players/')

class PlayerDelete(DeleteView):
	model = Player
	success_url = reverse_lazy('players:player_list')

def autoAdd():
	df = pd.read_excel('IITZL.xlsx', 'Redhawks')
	name = df['Name']
	freshers = df['Freshers']
	category = df['Category']
	venom = df['Venom']

	for i in range(0, len(name)):
		p = Player(name=name[i], squad='Redhawks', venom=venom[i], category=category[i], fresher_pg=freshers[i])
		p.save()

players/templates/players/player_confirm_delete.html
{% extends 'home/base.html' %}

{% block title %}
Delete {{ player }}?
{% endblock %}

{% block body %}
<form action="" method="post">
	{% csrf_token %}
    <p>Are you sure you want to delete "{{ player }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

players/templates/players/player_create.html
{% extends 'home/base.html' %}

{% block title %}
Add Player
{% endblock %}

{% block body %}
<h1 align='center'>Add Player</h1>
<br/><br/>
<form action="{% url 'players:addPlayer' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='200'>
		<tr align='left'>
			<th>Name:</th>
			<td><input type="text" name="name"></td>
		</tr>
		<tr align='left'>
			<th>Secret Snake Name:</th>
			<td><input type="text" name="ssn"></td>
		</tr>
		<tr align='left'>
			<th>
				<label>Squad:</label>
			</th>
			<td>
				<select name="squad">
  					{% for s in squads %}
						<option value='{{ s }}'>{{ s }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Venom(in ml):</label>
			</th>
			<td>
				<select name="venom">
  					{% for v in venoms %}
						<option value='{{ v }}'>{{ v }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Category:</label>
			</th>
			<td>
				<select name="category">
  					{% for c in categories %}
						<option value='{{ c }}'>{{ c }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Fresher/PG:</label>
			</th>
			<td>
				<select name="freshers">
  					{% for f in freshers %}
						<option value='{{ f }}'>{{ f }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Add Player'>
</form>
{% endblock %}

players/templates/players/player_detail.html
{% extends 'home/base.html' %}

{% block title %}
Player {{ player.name }}
{% endblock %}

{% block body %}
<h1>{{ player.name }} a.k.a. {{ player.ssn }}</h1>

<ul>
	<li>Squad : {{ player.squad }}</li>
	<li>Venom : {{ player.venom }}</li>
	<li>Category : {{ player.category }}</li>
	<li>Fresher/PG : {{ player.fresher_pg }}</li>
</ul>
<br/>
<br/>
{% if perms.net.can_add_player %}
<li><a href="{% url 'players:player_delete' player.name %}">Delete {{ player.name }}</a></li>
{% endif %}
{% endblock %}

players/templates/players/player_list.html
{% extends 'home/base.html' %}

{% block title %}
Players | Zeheri League
{% endblock %}

{% block addition %}
{% if perms.net.can_add_player %}
<li class=''>
	<a href="{% url 'players:player_create' %}">
		<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
		&nbsp; Add Player
	</a>
</li>
{% endif %}
{% endblock %}

{% block common %}
<h2 align='center'>Musketeers</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Venom</th>
		<th>Category</th>
		<th>Fresher/PG</th>
	</tr>
	{% for player in musketeers %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.name %}">{{ player.name }}</a></th>
			<td>{{ player.venom }} ml</td>
			<td>{{ player.category }}</td>
			<td>{{ player.fresher_pg }}</td>
		</tr>
	{% endfor %}
</ul>
</table>

<h2 align='center'>Redhawks</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Venom</th>
		<th>Category</th>
		<th>Fresher/PG</th>
	</tr>
	{% for player in redhawks %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.name %}">{{ player.name }}</a></th>
			<td>{{ player.venom }} ml</td>
			<td>{{ player.category }}</td>
			<td>{{ player.fresher_pg }}</td>
		</tr>
	{% endfor %}
</ul>
</table>

<h2 align='center'>Spartans</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Venom</th>
		<th>Category</th>
		<th>Fresher/PG</th>
	</tr>
	{% for player in spartans %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.name %}">{{ player.name }}</a></th>
			<td>{{ player.venom }} ml</td>
			<td>{{ player.category }}</td>
			<td>{{ player.fresher_pg }}</td>
		</tr>
	{% endfor %}
</ul>
</table>

<h2 align='center'>Thunder Strikers</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Venom</th>
		<th>Category</th>
		<th>Fresher/PG</th>
	</tr>
	{% for player in thunder %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.name %}">{{ player.name }}</a></th>
			<td>{{ player.venom }} ml</td>
			<td>{{ player.category }}</td>
			<td>{{ player.fresher_pg }}</td>
		</tr>
	{% endfor %}
</ul>
</table>
{% endblock %}

{% block special %}
{% endblock %}