home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.index, name='index'),
	path('admin/', views.admin, name='admin'),
	path('players/', views.players, name='players'),
	path('team/', views.team, name='team'),
	path('scores/', views.scores, name='scores'),
	path('leaderboard/', views.leaderboard, name='leaderboard'),
	path('rules/', views.rules, name='rules'),
]

iitpl_fantasy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('home.urls')),
    path('players/', include('players.urls')),
    path('team/', include('team.urls')),
    path('scores/', include('scores.urls')),
    path('leaderboard/', include('leaderboard.urls')),
]

leaderboard/urls.py
from django.urls import path
from . import views

app_name = 'leaderboard'

urlpatterns = [
	path('', views.index, name='index'),
	path('calculateScore/', views.calculateScore, name='calculateScore'),
	path('matchNumber/', views.matchNumber, name='matchNumber'),
	path('profile/', views.profile, name='profile'),
	path('resetUsers/', views.resetUsers, name='resetUsers'),
	path('substitutes/', views.substitutes, name='substitutes'),
	path('countSubstitutes/', views.countSubstitutes, name='countSubstitutes'),
	path('resetSubstitutes/', views.resetSubstitutes, name='resetSubstitutes'),
]

team/urls.py
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
	path('', views.selectMatch, name='selectMatch'),
	path('index/', views.index, name='index'),
	path('teamAddIndex/', views.teamAddIndex, name='teamAddIndex'),
	path('playerAdd/', views.playerAdd, name='playerAdd'),
	path('addPlayerLater/', views.addPlayerLater, name='addPlayerLater'),
	path('addBlackMamba/', views.addBlackMamba, name='addBlackMamba'),
	path('loadPlayer/', views.loadPlayer, name='loadPlayer'),
	path('updateMamba/', views.updateMamba, name='updateMamba'),
	path('update/<str:name>/', views.update, name='update'),
	path('deleteTeamPlayer/<str:name>/', views.deleteTeamPlayer, name='deleteTeamPlayer'),
	path('playerUpdate/', views.playerUpdate, name='playerUpdate'),
	path('resetTeam/', views.resetTeam, name='resetTeam'),
	path('listTeams/', views.listTeams, name='listTeams'),
	path('createTeams/', views.createTeams, name='createTeams'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect

# Create your views here.
def index(request):
	context = {}
	return render(request, 'home/index.html', context)

def admin(request):
	return redirect('/admin/')

def players(request):
	return redirect('/players/')

def team(request):
	return redirect('/team/')

def scores(request):
	return redirect('/scores/')

def leaderboard(request):
	return redirect('/leaderboard/')

def rules(request):
	return render(request, 'home/rules.html', {})

home/templates/home/base.html
<!DOCTYPE html>
<html lang='en'>

<head>
	<meta charset='UTF-8'>
	<title>{% block title %}ZeheriLeague{% endblock %}</title>
	{% load staticfiles %}
	{% block scripts %}
	{% endblock %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#topNavBar'>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
			</button>
			<a class="navbar-brand" href="{% url 'home:index' %}">IITZL</a>
		</div>

		<div class='collapse navbar-collapse' id='topNavBar'>

			<ul class='nav navbar-nav'>
				<li class=''>
					<a href="{% url 'home:players' %}">
						<span class='glyphicon glyphicon-knight' aria-hidden='true'></span>
						&nbsp; Players
					</a>
				</li>
			</ul>

			<ul class='nav navbar-nav navbar-right'>
				{% block addition %}
				{% endblock %}
				{% if user.is_authenticated %}
				<li class=''>
					{% if perms.net.can_add_player %}
						<a href="{% url 'home:admin' %}">
							<span class='glyphicon glyphicon-user' aria-hidden='true'></span>
							&nbsp; Admin
						</a>
					{% else %}
						<a href="{% url 'leaderboard:profile' %}">
							<span class='glyphicon glyphicon-user' aria-hidden='true'></span>
							&nbsp; {{ user }}
						</a>
					{% endif %}
				</li>
				{% endif %}
				{% if user.is_authenticated %}
					<li class=''>
						<a href="{% url 'logout' %}">
							<span class='glyphicon glyphicon-off' aria-hidden='true'></span>
							&nbsp; Logout
						</a>
					</li>
				{% else %}
					<li class=''>
						<a href="{% url 'login' %}">
							<span class='glyphicon glyphicon-ok' aria-hidden='true'></span>
							&nbsp; Login
						</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>

<body>
	{% if user.is_authenticated %}
		{% block body %}
		{% endblock %}
	{% else %}
		{% block special %}
			<h2 align='center'>You must be logged in to use this site</h2>
		{% endblock %}
	{% endif %}
	{% block common %}
	{% endblock %}
</body>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="">
                	<a href="{% url 'home:index' %}">
                		<span class='glyphicon glyphicon-home' aria-hidden='true'></span>
                		&nbsp; Home
                	</a>
                </li>
                <li class="">
                	<a href="{% url 'home:rules' %}">
                		&nbsp; Rules
                	</a>
                </li>
                {% if user.is_authenticated %}
                <li class="">
                	<a href="{% url 'home:team' %}">
                		&nbsp; Build Your Team
                	</a>
                </li>
                <li class="">
                	<a href="{% url 'team:listTeams' %}">
                		&nbsp; Previous Teams
                	</a>
                </li>
                {% if perms.net.can_add_player %}
                <li class="">
                	<a href="{% url 'home:scores' %}">
                		&nbsp; Scores
                	</a>
                </li>
                {% endif %}
                <li class="">
                	<a href="{% url 'home:leaderboard' %}">
                		&nbsp; Leaderboard
                	</a>
                </li>
                {% endif %}
            </ul>
            <ul class='nav navbar-nav navbar-right'>
            	<li class=''>
            		<a href='https://www.facebook.com/IITPremierLeague/'>Visit Facebook</a>
            	</li>
            	<li class=''>
            		<a href='https://www.facebook.com/shubham.chaudhary.35912'>Designed By: Shubham Chaudhary</a>
            	</li>
            </ul>
        </div>
    </div>
</nav>

home/templates/home/howto.html
{% extends 'home/base.html' %}

{% block common %}

{% endblock %}

{% block special %}
{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block addition %}
{% endblock %}

{% block body %}
<h2 align='center'>Welcome {{ user.get_full_name }} to ZeheriLeague</h2>
<h1 align='center'>Let the Venom Spill</h1>
<br/>
<h2 align='center'><a href="{% url 'home:team' %}">Build Your Team</a></h2>
<h2 align='center'><a href="{% url 'team:listTeams' %}">Previous Teams</a></h2>
<h2 align='center'><a href="{% url 'home:leaderboard' %}">Leaderboard</a></h2>
<h2 align='center'><a href="{% url 'home:rules' %}">Rules</a></h2>
<br/>
<h3 align='center'><a href="https://docs.google.com/spreadsheets/d/1L7EEzhld2c6hCZ53bbRXYcn2YjvULsBFbImoZZB8QoA/edit?usp=sharing">17th March Players' Points</a></h3>
{% endblock %}

{% block special %}
<p style="text-align:center;"><img src='/static/home/images/cobra.png' alt='IITZL Logo' width='200' height='200'></p>
<h1 align='center'>ZeheriLeague</h1>
<h3 align='center'>(The Official Fantasy League of IIT Premier League)</h3>
<br/>
<h3 align='center'><a href="https://goo.gl/forms/P7pZt3tqUpetkQyk2">Fill this form to get login credentials</a></h3>
<h3 align='center'><a href="https://docs.google.com/spreadsheets/d/1ODarkmH5Uftepn4kfJjBGhiTAZakwCszU1eZ0LEkpSw/edit?usp=sharing">List of Registered Users</a></h3>
{% endblock %}

{% block common %}
<br/>
<h3 align='center'>Results of 7th and 8th April will come at 10 A.M. on 9th April</h3>
<br/>
{% endblock %}

home/templates/home/rules.html
{% extends 'home/base.html' %}

{% block common %}
<h2 align='center'>Rules</h2>
<br/>
<h4>1. Zeheri Team should consist of atleast 3 Batsmen, 3 Bowler, 1 Wicket-Keeper and 1 All-Rounder</h4>
<h4>2. Overall venom shouldn't exceed 1100 ml</h4>
<h4>3. Atleast 2 UG Freshers and 1 PG student</h4>
<h4>4. 11 Players are to be selected</h4>
<h4>5. 1 Player will be selected as Black Mamba player</h4>
<h4>6. 20 number of substitutions are allowed in the entire league</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;6.1. The number of changes between two freezed teams will be counted as substitutions</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;6.2. UG Fresher replaced with UG Fresher will not be counted as substitution</h4>
<br/>
<h2 align='center'>Points' Structure</h2>
<br/>
<h3>1. Batsman</h3>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;1.1. 1 Run: +1 Point</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;1.2. +(Runs - Balls) Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;1.3. 1 Six: +2 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;1.4. 1 Four: +1 Point</h4>
<h3>2. Bowler</h3>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;2.1. 1st Wicket: +10 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;2.2. 2nd Wicket: +20 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;2.3. 3rd Wicket: +30 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;2.4. 4th or above: +30 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;2.5. +(7 x Overs - Runs) Points</h4>
<h3>3. Fielder</h3>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;3.1. 1 Catch-Out: +5 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;3.2. 1 Stump: +5 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;3.3. 1 Run-Out: +5 Points</h4>
<h3>4. Extra Points</h3>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;4.1. For each playing player in your team: +2 Points</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;4.2. Black Mamba player: 2x Points</h4>
{% endblock %}

{% block special %}
{% endblock %}