home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.index, name='index'),
	path('admin/', views.admin, name='admin'),
	path('players/', views.players, name='players'),
	path('team/', views.team, name='team'),
	path('scores/', views.scores, name='scores'),
	path('leaderboard/', views.leaderboard, name='leaderboard'),
	path('rules/', views.rules, name='rules'),
]

iitpl_fantasy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('home.urls')),
    path('players/', include('players.urls')),
    path('team/', include('team.urls')),
    path('scores/', include('scores.urls')),
    path('leaderboard/', include('leaderboard.urls')),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
	path('', views.playerList, name='player_list'),
	path('create/', views.createPlayer, name='player_create'),
	path('add/', views.addPlayer, name='addPlayer'),
	path('delete/<pk>/', views.PlayerDelete.as_view(), name='player_delete'),
	path('<pk>/', views.PlayerDetail.as_view(), name='player_detail'),
]

scores/urls.py
from django.urls import path
from . import views

app_name = 'scores'

urlpatterns = [
	path('', views.index, name='index'),
	path('bowling/', views.BallList.as_view(), name='bowling'),
	path('batting/', views.BatList.as_view(), name='batting'),
	path('fielding/', views.FieldList.as_view(), name='fielding'),
	path('playing/', views.PlayedList.as_view(), name='playing'),
	path('createBat/', views.createBat, name='createBat'),
	path('createBall/', views.createBall, name='createBall'),
	path('createField/', views.createField, name='createField'),
	path('createPlay/', views.createPlay, name='createPlay'),
	path('addBat/', views.addBat, name='addBat'),
	path('addBall/', views.addBall, name='addBall'),
	path('addField/', views.addField, name='addField'),
	path('addPlay/', views.addPlay, name='addPlay'),
	path('batDelete/<pk>/', views.BatDelete.as_view(), name='batDelete'),
	path('ballDelete/<pk>/', views.BallDelete.as_view(), name='ballDelete'),
	path('fieldDelete/<pk>/', views.FieldDelete.as_view(), name='fieldDelete'),
	path('playDelete/<pk>/', views.PlayDelete.as_view(), name='playDelete'),
	path('loadPlayer/', views.loadPlayer, name='loadPlayer'),
]

players/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
	name = models.CharField(max_length=20, primary_key=True)
	ssn = models.CharField(max_length=20, blank=True)
	squad = models.CharField(max_length=20, blank=True)
	category = models.CharField(max_length=15, blank=True)
	venom = models.IntegerField(default=0)
	fresher_pg = models.CharField(max_length=10, blank=True)

	def __str__(self):
		return self.name

class PlayerStats(models.Model):
	player = models.OneToOneField(Player, on_delete=models.CASCADE)
	runs = models.IntegerField(default=0)
	matches = models.IntegerField(default=0)
	highest_run = models.IntegerField(default=0)
	balls = models.IntegerField(default=0)
	wickets = models.IntegerField(default=0)
	run_conceded = models.IntegerField(default=0)
	highest_wicket = models.IntegerField(default=0)

	def __str__(self):
		return self.player.name

scores/models.py
from django.db import models
from players.models import Player
# Create your models here.
class BatRecord(models.Model):
	player = models.OneToOneField(Player, on_delete=models.CASCADE, primary_key=True)
	runs = models.IntegerField(default=0)
	balls = models.IntegerField(default=0)
	fours = models.IntegerField(default=0)
	sixes = models.IntegerField(default=0)
	points = models.FloatField(default=0)
	match = models.IntegerField(default=0)

	def __str__(self):
		return self.player.name + ' Batsman ' + str(self.points)

class BallRecord(models.Model):
	player = models.OneToOneField(Player, on_delete=models.CASCADE, primary_key=True)
	balls = models.IntegerField(default=0)
	runs = models.IntegerField(default=0)
	wickets = models.IntegerField(default=0)
	points = models.FloatField(default=0)
	match = models.IntegerField(default=0)

	def __str__(self):
		return self.player.name + ' Bowler ' + str(self.points)

class FieldRecord(models.Model):
	player = models.OneToOneField(Player, on_delete=models.CASCADE, primary_key=True)
	catches = models.IntegerField(default=0)
	stumps = models.IntegerField(default=0)
	run_outs = models.IntegerField(default=0)
	points = models.FloatField(default=0)
	match = models.IntegerField(default=0)

	def __str__(self):
		return self.player.name + ' Fielder ' + str(self.points)

class PlayedRecord(models.Model):
	player = models.OneToOneField(Player, on_delete=models.CASCADE, primary_key=True)
	match = models.IntegerField(default=0)
	points = models.IntegerField(default=2)

	def __str__(self):
		return self.player.name + ' Played ' + str(self.points)

scores/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView
from django.views.generic import ListView
from .models import BatRecord, BallRecord, FieldRecord, PlayedRecord
from players.models import Player
from django.urls import reverse_lazy
# Create your views here.

def index(request):
	return render(request, 'scores/index.html', {})

class BatList(ListView):
	queryset = BatRecord.objects.order_by('match', 'points').reverse()
	context_object_name = 'batrecord_list'

class BallList(ListView):
	queryset = BallRecord.objects.order_by('match', 'points').reverse()
	context_object_name = 'ballrecord_list'

class FieldList(ListView):
	queryset = FieldRecord.objects.order_by('match', 'points').reverse()
	context_object_name = 'fieldrecord_list'

class PlayedList(ListView):
	queryset = PlayedRecord.objects.order_by('match', 'points').reverse()
	context_object_name = 'playedrecord_list'

class BatDelete(DeleteView):
	model = BatRecord
	success_url = reverse_lazy('scores:batting')

class BallDelete(DeleteView):
	model = BallRecord
	success_url = reverse_lazy('scores:bowling')

class FieldDelete(DeleteView):
	model = FieldRecord
	success_url = reverse_lazy('scores:fielding')

class PlayDelete(DeleteView):
	model = PlayedRecord
	success_url = reverse_lazy('scores:playing')

def createBat(request):
	squads = ['Spartans', 'Musketeers', 'Redhawks', 'Thunder Strikers']
	return render(request, 'scores/addBat.html', {'squads' : squads})

def addBat(request):
	player = Player.objects.get(name=request.POST['player'])
	runs = int(request.POST['runs'])
	balls = int(request.POST['balls'])
	fours = int(request.POST['fours'])
	sixes = int(request.POST['sixes'])
	match = int(request.POST['match'])
	points = 2 * runs - balls + 2 * sixes + fours
	note = BatRecord(player=player, runs=runs, balls=balls, sixes=sixes, fours=fours, points=points, match=match)
	note.save()
	return redirect('/scores/batting/')

def createBall(request):
	squads = ['Spartans', 'Musketeers', 'Redhawks', 'Thunder Strikers']
	return render(request, 'scores/addBall.html', {'squads' : squads})

def addBall(request):
	player = Player.objects.get(name=request.POST['player'])
	runs = int(request.POST['runs'])
	balls = int(request.POST['balls'])
	wickets = int(request.POST['wickets'])
	match = int(request.POST['match'])
	wp = 0
	if wickets == 1:
		wp = 10
	elif wickets == 2:
		wp = 30
	elif wickets == 3:
		wp = 60
	elif wickets > 3:
		wp = 60 + (wickets - 3) * 30
	points = 7 * float(balls / 6) - runs + wp
	note = BallRecord(player=player, runs=runs, balls=balls, wickets=wickets, points=points, match=match)
	note.save()
	return redirect('/scores/bowling/')

def createField(request):
	squads = ['Spartans', 'Musketeers', 'Redhawks', 'Thunder Strikers']
	return render(request, 'scores/addField.html', {'squads' : squads})

def addField(request):
	player = Player.objects.get(name=request.POST['player'])
	stumps = int(request.POST['stumps'])
	catches = int(request.POST['catches'])
	run_outs = int(request.POST['run_outs'])
	match = int(request.POST['match'])
	points = 5 * stumps + 5 * catches + 5 * run_outs
	note = FieldRecord(player=player, stumps=stumps, catches=catches, run_outs=run_outs, points=points, match=match)
	note.save()
	return redirect('/scores/fielding/')

def createPlay(request):
	squads = ['Spartans', 'Musketeers', 'Redhawks', 'Thunder Strikers']
	return render(request, 'scores/addPlay.html', {'squads' : squads})

def addPlay(request):
	player = Player.objects.get(name=request.POST['player'])
	match = int(request.POST['match'])
	note = PlayedRecord(player=player, match=match)
	note.save()
	return redirect('/scores/playing/')

def loadPlayer(request):
	squad = request.GET.get('squad')
	players = Player.objects.filter(squad=squad)
	context = {'players' : players}
	return render(request, 'team/player_options.html', context)

scores/templates/scores/addBall.html
{% extends 'home/base.html' %}

{% block title %}
Add Bowler Record
{% endblock %}

{% block body %}
<h1 align='center'>Add Bowler Record</h1>
<br/>
<form action="{% url 'scores:addBall' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='200'>
		<tr align='left'>
			<th>
				<label>Squad:</label>
			</th>
			<td>
				<select name="squad" required id="id_squad">
					<option value="">---------</option>
  					{% for s in squads %}
						<option value='{{ s }}'>{{ s }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Player:</label>
			</th>
			<td>
				<select name="player" required id="id_player">
  					<option value="" selected>---------</option>
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>Match:</th>
			<td><input type="number" name="match"></td>
		</tr>
		<tr align='left'>
			<th>Balls:</th>
			<td><input type="number" name="balls"></td>
		</tr>
		<tr align='left'>
			<th>Runs:</th>
			<td><input type="number" name="runs"></td>
		</tr>
		<tr align='left'>
			<th>Wickets:</th>
			<td><input type="number" name="wickets"></td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Add Player Record'>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	$('#id_squad').change(function () {
		var url = "{% url 'scores:loadPlayer' %}";
		var squad = $(this).val();

		$.ajax({
			url: url,
			data: {
				'squad' : squad
			},
			success: function (data){
				$('#id_player').html(data);
			}
		});
	});
</script>
{% endblock %}

scores/templates/scores/addBat.html
{% extends 'home/base.html' %}

{% block title %}
Add Batsman Record
{% endblock %}

{% block body %}
<h1 align='center'>Add Batsman Record</h1>
<br/>
<form action="{% url 'scores:addBat' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='200'>
		<tr align='left'>
			<th>
				<label>Squad:</label>
			</th>
			<td>
				<select name="squad" required id="id_squad">
					<option value="">---------</option>
  					{% for s in squads %}
						<option value='{{ s }}'>{{ s }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Player:</label>
			</th>
			<td>
				<select name="player" required id="id_player">
  					<option value="" selected>---------</option>
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>Match:</th>
			<td><input type="number" name="match"></td>
		</tr>
		<tr align='left'>
			<th>Runs:</th>
			<td><input type="number" name="runs"></td>
		</tr>
		<tr align='left'>
			<th>Balls:</th>
			<td><input type="number" name="balls"></td>
		</tr>
		<tr align='left'>
			<th>Fours:</th>
			<td><input type="number" name="fours"></td>
		</tr>
		<tr align='left'>
			<th>Sixes:</th>
			<td><input type="number" name="sixes"></td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Add Player Record'>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	$('#id_squad').change(function () {
		var url = "{% url 'scores:loadPlayer' %}";
		var squad = $(this).val();

		$.ajax({
			url: url,
			data: {
				'squad' : squad
			},
			success: function (data){
				$('#id_player').html(data);
			}
		});
	});
</script>
{% endblock %}

scores/templates/scores/addField.html
{% extends 'home/base.html' %}

{% block title %}
Add Fielder Record
{% endblock %}

{% block body %}
<h1 align='center'>Add Fielder Record</h1>
<br/>
<form action="{% url 'scores:addField' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='200'>
		<tr align='left'>
			<th>
				<label>Squad:</label>
			</th>
			<td>
				<select name="squad" required id="id_squad">
					<option value="">---------</option>
  					{% for s in squads %}
						<option value='{{ s }}'>{{ s }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Player:</label>
			</th>
			<td>
				<select name="player" required id="id_player">
  					<option value="" selected>---------</option>
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>Match:</th>
			<td><input type="number" name="match"></td>
		</tr>
		<tr align='left'>
			<th>Stumps:</th>
			<td><input type="number" name="stumps"></td>
		</tr>
		<tr align='left'>
			<th>Catches:</th>
			<td><input type="number" name="catches"></td>
		</tr>
		<tr align='left'>
			<th>Run Outs:</th>
			<td><input type="number" name="run_outs"></td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Add Player Record'>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	$('#id_squad').change(function () {
		var url = "{% url 'scores:loadPlayer' %}";
		var squad = $(this).val();

		$.ajax({
			url: url,
			data: {
				'squad' : squad
			},
			success: function (data){
				$('#id_player').html(data);
			}
		});
	});
</script>
{% endblock %}

scores/templates/scores/addPlay.html
{% extends 'home/base.html' %}

{% block title %}
Add Played Record
{% endblock %}

{% block body %}
<h1 align='center'>Add Played Record</h1>
<br/>
<form action="{% url 'scores:addPlay' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='200'>
		<tr align='left'>
			<th>
				<label>Squad:</label>
			</th>
			<td>
				<select name="squad" required id="id_squad">
					<option value="">---------</option>
  					{% for s in squads %}
						<option value='{{ s }}'>{{ s }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Player:</label>
			</th>
			<td>
				<select name="player" required id="id_player">
  					<option value="" selected>---------</option>
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>Match:</th>
			<td><input type="number" name="match"></td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Add Player Record'>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	$('#id_squad').change(function () {
		var url = "{% url 'scores:loadPlayer' %}";
		var squad = $(this).val();

		$.ajax({
			url: url,
			data: {
				'squad' : squad
			},
			success: function (data){
				$('#id_player').html(data);
			}
		});
	});
</script>
{% endblock %}

scores/templates/scores/ballrecord_confirm_delete.html
{% extends 'home/base.html' %}

{% block title %}
Delete {{ ballrecord }}?
{% endblock %}

{% block body %}
<form action="" method="post">
	{% csrf_token %}
    <p>Are you sure you want to delete "{{ ballrecord }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

scores/templates/scores/ballrecord_list.html
{% extends 'home/base.html' %}

{% block title %}
Bowler | Match Records
{% endblock %}

{% block addition %}
<li class=''>
	<a href="{% url 'scores:createBall' %}">
		<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
		&nbsp; Add Bowler Record
	</a>
</li>
{% endblock %}

{% block body %}
<h2 align='center'>Bowler</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Squad</th>
		<th>Match</th>
		<th>Balls</th>
		<th>Runs</th>
		<th>Wickets</th>
		<th>Points</th>
		<th>Delete?</th>
	</tr>
	{% for player in ballrecord_list %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.player.name %}">{{ player.player.name }}</a></th>
			<td>{{ player.player.squad }}</td>
			<td>{{ player.match }}</td>
			<td>{{ player.balls }}</td>
			<td>{{ player.runs }}</td>
			<td>{{ player.wickets }}</td>
			<td>{{ player.points }}</td>
			<td><a href="{% url 'scores:ballDelete' player.player %}">Yes</td>
		</tr>
	{% endfor %}
</ul>
</table>
{% endblock %}

scores/templates/scores/batrecord_confirm_delete.html
{% extends 'home/base.html' %}

{% block title %}
Delete {{ batrecord }}?
{% endblock %}

{% block body %}
<form action="" method="post">
	{% csrf_token %}
    <p>Are you sure you want to delete "{{ batrecord }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

scores/templates/scores/batrecord_list.html
{% extends 'home/base.html' %}

{% block title %}
Batsman | Match Records
{% endblock %}

{% block addition %}
<li class=''>
	<a href="{% url 'scores:createBat' %}">
		<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
		&nbsp; Add Batsman Record
	</a>
</li>
{% endblock %}

{% block body %}
<h2 align='center'>Batsman</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Squad</th>
		<th>Match</th>
		<th>Runs</th>
		<th>Balls</th>
		<th>Fours</th>
		<th>Sixes</th>
		<th>Points</th>
		<th>Delete?</th>
	</tr>
	{% for player in batrecord_list %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.player.name %}">{{ player.player.name }}</a></th>
			<td>{{ player.player.squad }}</td>
			<td>{{ player.match }}</td>
			<td>{{ player.runs }}</td>
			<td>{{ player.balls }}</td>
			<td>{{ player.fours }}</td>
			<td>{{ player.sixes }}</td>
			<td>{{ player.points }}</td>
			<td><a href="{% url 'scores:batDelete' player.player %}">Yes</td>
		</tr>
	{% endfor %}
</ul>
</table>
{% endblock %}

scores/templates/scores/fieldrecord_confirm_delete.html
{% extends 'home/base.html' %}

{% block title %}
Delete {{ fieldrecord }}?
{% endblock %}

{% block body %}
<form action="" method="post">
	{% csrf_token %}
    <p>Are you sure you want to delete "{{ fieldrecord }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

scores/templates/scores/fieldrecord_list.html
{% extends 'home/base.html' %}

{% block title %}
Fielder | Match Records
{% endblock %}

{% block addition %}
<li class=''>
	<a href="{% url 'scores:createField' %}">
		<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
		&nbsp; Add Fielder Record
	</a>
</li>
{% endblock %}

{% block body %}
<h2 align='center'>Fielder</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Squad</th>
		<th>Match</th>
		<th>Stumps</th>
		<th>Run Outs</th>
		<th>Catches</th>
		<th>Points</th>
		<th>Delete?</th>
	</tr>
	{% for player in fieldrecord_list %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.player.name %}">{{ player.player.name }}</a></th>
			<td>{{ player.player.squad }}</td>
			<td>{{ player.match }}</td>
			<td>{{ player.stumps }}</td>
			<td>{{ player.run_outs }}</td>
			<td>{{ player.catches }}</td>
			<td>{{ player.points }}</td>
			<td><a href="{% url 'scores:fieldDelete' player.player %}">Yes</td>
		</tr>
	{% endfor %}
</ul>
</table>
{% endblock %}

scores/templates/scores/index.html
{% extends 'home/base.html' %}

{% block addition %}
{% endblock %}

{% block body %}
<h2 align='center'><a href="{% url 'scores:batting' %}">Batsman</a></h2>
<h2 align='center'><a href="{% url 'scores:bowling' %}">Bowler</a></h2>
<h2 align='center'><a href="{% url 'scores:fielding' %}">Fielder</a></h2>
<h2 align='center'><a href="{% url 'scores:playing' %}">Player</a></h2>
{% endblock %}

scores/templates/scores/playedrecord_confirm_delete.html
{% extends 'home/base.html' %}

{% block title %}
Delete {{ playedrecord }}?
{% endblock %}

{% block body %}
<form action="" method="post">
	{% csrf_token %}
    <p>Are you sure you want to delete "{{ playedrecord }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

scores/templates/scores/playedrecord_list.html
{% extends 'home/base.html' %}

{% block title %}
Playing | Match Records
{% endblock %}

{% block addition %}
<li class=''>
	<a href="{% url 'scores:createPlay' %}">
		<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
		&nbsp; Add Played Record
	</a>
</li>
{% endblock %}

{% block body %}
<h2 align='center'>Players</h2>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Squad</th>
		<th>Match</th>
		<th>Points</th>
		<th>Delete?</th>
	</tr>
	{% for player in playedrecord_list %}
		<tr>
			<th><a href="{% url 'players:player_detail' player.player.name %}">{{ player.player.name }}</a></th>
			<td>{{ player.player.squad }}</td>
			<td>{{ player.match }}</td>
			<td>{{ player.points }}</td>
			<td><a href="{% url 'scores:playDelete' player.player %}">Yes</td>
		</tr>
	{% endfor %}
</ul>
</table>
{% endblock %}

scores/templates/scores/player_options.html
{% for p in players %}
<option value="{{ p }}">{{ p }}</option>
{% endfor %}