home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.index, name='index'),
	path('admin/', views.admin, name='admin'),
	path('players/', views.players, name='players'),
	path('team/', views.team, name='team'),
	path('scores/', views.scores, name='scores'),
	path('leaderboard/', views.leaderboard, name='leaderboard'),
	path('rules/', views.rules, name='rules'),
]

iitpl_fantasy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('home.urls')),
    path('players/', include('players.urls')),
    path('team/', include('team.urls')),
    path('scores/', include('scores.urls')),
    path('leaderboard/', include('leaderboard.urls')),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
	path('', views.playerList, name='player_list'),
	path('create/', views.createPlayer, name='player_create'),
	path('add/', views.addPlayer, name='addPlayer'),
	path('delete/<pk>/', views.PlayerDelete.as_view(), name='player_delete'),
	path('<pk>/', views.PlayerDetail.as_view(), name='player_detail'),
]

team/urls.py
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
	path('', views.selectMatch, name='selectMatch'),
	path('index/', views.index, name='index'),
	path('teamAddIndex/', views.teamAddIndex, name='teamAddIndex'),
	path('playerAdd/', views.playerAdd, name='playerAdd'),
	path('addPlayerLater/', views.addPlayerLater, name='addPlayerLater'),
	path('addBlackMamba/', views.addBlackMamba, name='addBlackMamba'),
	path('loadPlayer/', views.loadPlayer, name='loadPlayer'),
	path('updateMamba/', views.updateMamba, name='updateMamba'),
	path('update/<str:name>/', views.update, name='update'),
	path('deleteTeamPlayer/<str:name>/', views.deleteTeamPlayer, name='deleteTeamPlayer'),
	path('playerUpdate/', views.playerUpdate, name='playerUpdate'),
	path('resetTeam/', views.resetTeam, name='resetTeam'),
	path('listTeams/', views.listTeams, name='listTeams'),
	path('createTeams/', views.createTeams, name='createTeams'),
]

players/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
	name = models.CharField(max_length=20, primary_key=True)
	ssn = models.CharField(max_length=20, blank=True)
	squad = models.CharField(max_length=20, blank=True)
	category = models.CharField(max_length=15, blank=True)
	venom = models.IntegerField(default=0)
	fresher_pg = models.CharField(max_length=10, blank=True)

	def __str__(self):
		return self.name

class PlayerStats(models.Model):
	player = models.OneToOneField(Player, on_delete=models.CASCADE)
	runs = models.IntegerField(default=0)
	matches = models.IntegerField(default=0)
	highest_run = models.IntegerField(default=0)
	balls = models.IntegerField(default=0)
	wickets = models.IntegerField(default=0)
	run_conceded = models.IntegerField(default=0)
	highest_wicket = models.IntegerField(default=0)

	def __str__(self):
		return self.player.name

team/models.py
from django.db import models
from players.models import Player
from django.contrib.auth.models import User

# Create your models here.
class Team(models.Model):
	name = models.CharField(max_length=40, primary_key=True, blank=True)
	black_mamba = models.ForeignKey(Player, on_delete=models.CASCADE)
	score = models.IntegerField(default=0)

	def __str__(self):
		return self.name

class PlayerTeam(models.Model):
	name = models.CharField(max_length=40, primary_key=True, blank=True)
	player = models.ForeignKey(Player, on_delete=models.CASCADE)
	team = models.ForeignKey(Team, on_delete=models.CASCADE, blank=True)
	score = models.IntegerField(default=0)

	def __str__(self):
		return self.name

class UserMatch(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	match = models.CharField(max_length=3, default='1')
	player = models.CharField(max_length=30, blank=True)

	def __str__(self):
		return self.user

team/views.py
from django.shortcuts import render, redirect
from .models import Team, PlayerTeam, UserMatch
from django.contrib.auth.models import User
from players.models import Player
from leaderboard.models import UserData
from django.http import HttpResponse
import time

# Create your views here.
initial_anti_venom = 1100
squad_length = 11
squad_list = ['Musketeers', 'Redhawks', 'Spartans', 'Thunder Strikers']
# dummy = []

def index(request):
	um = UserMatch(user=request.user, match=request.POST['match'])
	um.save()
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	if team.exists():
		team_players = PlayerTeam.objects.filter(team=team[0])
		if len(team_players) > squad_length:
			team.delete()
			return render(request, 'team/team_create.html', {})
		context = {'team_players' : team_players, 'team' : team[0]}
		return render(request, 'team/final_team.html', context)
	else:
		match = int(um.match) - 1
		while match > 0:
			name = str(request.user) + ' match#' + str(match)
			team = Team.objects.filter(name=name)
			if team.exists():
				break
			match -= 1
		if match == 0:
			return render(request, 'team/team_create.html', {})
		else:
			team = team[0]
			name = str(request.user) + ' match#' + um.match
			new_team = Team(name=name, black_mamba=team.black_mamba)
			new_team.save()
			team_players = PlayerTeam.objects.filter(team=team)
			for team_player in team_players:
				player = team_player.player
				name = str(new_team) + str(player)
				new_team_player = PlayerTeam(team=new_team, player=player, name=name)
				new_team_player.save()
			new_team_players = PlayerTeam.objects.filter(team=new_team)
			context = {'team_players' : new_team_players, 'team' : new_team}
			return render(request, 'team/final_team.html', context)

def selectMatch(request):
	u = UserData.objects.filter(user=request.user)
	if not u.exists():
		ud = UserData(user=request.user)
		ud.save()
	ud = UserData.objects.get(user=request.user)
	info = ud.substitutes
	return render(request, 'team/match.html', {'info' : info})

def teamAddIndex(request):
	squads = squad_list
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	if team.exists():
		team.delete()
	team_players = PlayerTeam.objects.none()
	context = {'team_players' : team_players, 'squads' : squads, 'count' : squad_length, 'anti_venom' : initial_anti_venom}
	return render(request, 'team/building_team.html', context)

def addPlayerLater(request):
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	team = team[0]
	team_players = PlayerTeam.objects.filter(team=team)
	if len(team_players) == squad_length:
		return render(request, 'team/final_team.html', {'team_players' : team_players, 'team' : team})
	count = len(team_players)
	venom = 0
	for tp in team_players:
		venom += tp.player.venom
	anti_venom = initial_anti_venom - venom
	squads = squad_list
	count = squad_length - count
	context = {'team_players' : team_players, 'team' : team, 'squads' : squads, 'count' : count, 'anti_venom' : anti_venom}
	return render(request, 'team/building_team.html', context)

def checkValidity(team_players, team):
	players = []
	for tp in team_players:
		players.append(tp.player)
	error = ''
	if sum(player.category == 'Batsman' for player in players) < 3:
		error = 'Less Number of Batsmen, '
	if sum(player.category == 'Bowler' for player in players) < 3:
		error += 'Less Number of Bowlers, '
	if sum(player.category == 'Wicket-Keeper' for player in players) < 1:
		error += 'No Wicket-Keeper, '
	if sum(player.category == 'All-Rounder' for player in players) < 1:
		error += 'No All-Rounder, '
	if sum(player.fresher_pg == 'Fresher' for player in players) < 2:
		error += 'Less Number of UG Freshers, '
	if sum(player.fresher_pg == 'PG' for player in players) < 1:
		error += 'No PG'
	return error

def playerAdd(request):
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	if team.exists():
		team = team[0]
		player = Player.objects.get(pk=request.POST['player'])
		name = str(team) + str(player)
		team_player = PlayerTeam(team=team, player=player, name=name)
		team_player.save()
		team_players = PlayerTeam.objects.filter(team=team)
		count = len(team_players)
		venom = 0
		for tp in team_players:
			venom += tp.player.venom
		anti_venom = initial_anti_venom - venom
		if anti_venom < 0:
			team_player.delete()
			return HttpResponse('<h2>Too much venom</h2>')
		if count == squad_length:
			error = checkValidity(team_players, team)
			if error == '':
				return render(request, 'team/addBlackMamba.html', {'players' : team_players})
			else:
				team_player.delete()
				return HttpResponse('<h2>' + error + '</h2>')
		else:
			squads = squad_list
			count = squad_length - count
			context = {'team_players' : team_players, 'team' : team, 'squads' : squads, 'count' : count, 'anti_venom' : anti_venom}
			return render(request, 'team/building_team.html', context)
	else:
		player = Player.objects.get(pk=request.POST['player'])
		team = Team(name=name, black_mamba=player)
		team.save()
		name = str(team) + str(player)
		team_player = PlayerTeam(team=team, player=player, name=name)
		team_player.save()
		squads = squad_list
		count = squad_length - 1
		anti_venom = initial_anti_venom - player.venom
		team_players = PlayerTeam.objects.filter(team=team)
		context = {'team_players' : team_players, 'squads' : squads, 'count' : count, 'anti_venom' : anti_venom}
		return render(request, 'team/building_team.html', context)

def loadPlayer(request):
	squad = request.GET.get('squad')
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	exclude = []
	if team.exists():
		players = list(PlayerTeam.objects.filter(team=team[0]))
		exclude = [player.player.name for player in players]
	players = Player.objects.filter(squad=squad).exclude(name__in=exclude).order_by('venom').reverse()
	context = {'players' : players}
	return render(request, 'team/player_options.html', context)

def addBlackMamba(request):
	player = Player.objects.get(pk=request.POST['player'])
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	team = team[0]
	team.black_mamba = player
	team.save()
	return redirect('/team/')

def deleteTeamPlayer(request, name):
	um = UserMatch.objects.get(user=request.user)
	team_name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=team_name)
	player = Player.objects.get(name=name)
	team_player = PlayerTeam.objects.filter(team=team[0], player=player)
	team_player = team_player[0]
	if team_player.player.name == team[0].black_mamba.name:
		team[0].black_mamba = None
	team_player.delete()
	team_players = PlayerTeam.objects.filter(team=team[0])
	count = len(team_players)
	venom = 0
	for tp in team_players:
		venom += tp.player.venom
	anti_venom = initial_anti_venom - venom
	squads = squad_list
	count = squad_length - count
	context = {'team_players' : team_players, 'team' : team, 'squads' : squads, 'count' : count, 'anti_venom' : anti_venom}
	return render(request, 'team/building_team.html', context)

def updateMamba(request):
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	team_players = PlayerTeam.objects.filter(team=team[0])
	return render(request, 'team/addBlackMamba.html', {'players' : team_players})

def update(request, name):
	um = UserMatch.objects.get(user=request.user)
	team_name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=team_name)
	player = Player.objects.get(name=name)
	team_player = PlayerTeam.objects.filter(team=team[0], player=player)
	team_player = team_player[0]
	um.player = str(team_player)
	um.save()
	squads = squad_list
	return render(request, 'team/update.html', {'squads' : squads})

def playerUpdate(request):
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	team = team[0]
	player = Player.objects.get(pk=request.POST['player'])
	name = str(team) + str(player) 
	team_player = PlayerTeam(team=team, player=player, name=name)
	team_player.save()
	venom = 0
	p = PlayerTeam.objects.get(name=um.player)
	team_players = PlayerTeam.objects.filter(team=team).exclude(player=p.player)
	for tp in team_players:
		venom += tp.player.venom
	anti_venom = initial_anti_venom - venom
	if anti_venom < 0:
		team_player.delete()
		um.player = ''
		um.save()
		return HttpResponse('<h2>Too much venom</h2>')
	error = checkValidity(team_players, team)
	if error == '' or len(team_players) < squad_length:
		p.delete()
		um.player = ''
		um.save()
		if p.player.name == team.black_mamba.name:
			return render(request, 'team/addBlackMamba.html', {'players' : team_players})
		else:
			return render(request, 'team/final_team.html', {'team_players' : team_players, 'team' : team})
	else:
		team_player.delete()
		um.player = ''
		um.save()
		return HttpResponse('<h2>' + error + '</h2>')

def resetTeam(request):
	um = UserMatch.objects.get(user=request.user)
	name = str(request.user) + ' match#' + um.match
	team = Team.objects.filter(name=name)
	team = team[0]
	team_players = PlayerTeam.objects.filter(team=team)
	team_players.delete()
	team.delete()
	return render(request, 'team/team_create.html', {})

def listTeams(request):
	matches = ['1', '2', '3', '4', '5', '6']
	teams = []
	black_mambas = []
	for match in matches:
		name = str(request.user) + ' match#' + match
		team = Team.objects.filter(name=name)
		if not team.exists():
			continue
		team = team[0]
		black_mambas.append(team.black_mamba)
		team_players = PlayerTeam.objects.filter(team=team)
		x = []
		for team_player in team_players:

team/templates/team/addBlackMamba.html
{% extends 'home/base.html' %}

{% block title %}
Select Black Mamba
{% endblock %}

{% block body %}
<h1 align='center'>Select Black Mamba</h1>
<br/>
<form action="{% url 'team:addBlackMamba' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='200'>
		<tr align='left'>
			<th>
				<label>Player:</label>
			</th>
			<td>
				<select name="player">
  					{% for p in players %}
						<option value='{{ p.player.name }}'>{{ p.player.name }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Select Black Mamba'>
</form>
{% endblock %}

team/templates/team/building_team.html
{% extends 'home/base.html' %}

{% block title %}
Create Team
{% endblock %}

{% block body %}
<h1 align='center'>Create Team</h1>
<br/>
<h3 align='center'>{{ count }} More Players To Be Added({{ anti_venom }} ml Anti-Venom left)</h3>
<form action="{% url 'team:playerAdd' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='350'>
		<tr align='left'>
			<th>
				<label>Squad:</label>
			</th>
			<td>
				<select name="squad" required id="id_squad">
					<option value="">---------</option>
  					{% for s in squads %}
						<option value='{{ s }}'>{{ s }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Player:</label>
			</th>
			<td>
				<select name="player" required id="id_player">
  					<option value="" selected>---------</option>
				</select>
			</td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Add Player'>
</form>

<h2 align='center'>Players Selected</h2>
<br/>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Squad</th>
		<th>Venom</th>
		<th>Category</th>
		<th>Fresher/PG</th>
		<th>Delete?</th>
	</tr>
	{% for team_player in team_players %}
		<tr>
			<th><a href="{% url 'players:player_detail' team_player.player.name %}">{{ team_player.player.name }}</a></th>
			<td>{{ team_player.player.squad }}</td>
			<td>{{ team_player.player.venom }} ml</td>
			<td>{{ team_player.player.category }}</td>
			<td>{{ team_player.player.fresher_pg }}</td>
			<td><a href="{% url 'team:deleteTeamPlayer' team_player.player.name %}">Yes</td>
		</tr>
	{% endfor %}
</ul>
</table>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	$('#id_squad').change(function () {
		var url = "{% url 'team:loadPlayer' %}";
		var squad = $(this).val();

		$.ajax({
			url: url,
			data: {
				'squad' : squad
			},
			success: function (data){
				$('#id_player').html(data);
			}
		});
	});
</script>
{% endblock %}

team/templates/team/final_team.html
{% extends 'home/base.html' %}

{% block title %}
Team Created
{% endblock %}

{% block addition %}
<li class=''>
	<a href="{% url 'team:addPlayerLater' %}">
		<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
		&nbsp; Add Player
	</a>
</li>
<li class=''>
	<a href="{% url 'team:updateMamba' %}">
		<span class='glyphicon glyphicon-wrench' aria-hidden='true'></span>
		&nbsp; Update Black Mamba
	</a>
</li>
<li class=''>
	<a href="{% url 'team:resetTeam' %}" onclick="return confirm('Are you sure?')">
		<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>
		&nbsp; Reset Team
	</a>
</li>
{% endblock %}

{% block body %}
<h2 align='center'>Team Created</h2>
<h3 align='center'>Black Mamba: {{ team.black_mamba }}</h3>
<br/>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Squad</th>
		<th>Venom</th>
		<th>Category</th>
		<th>Fresher/PG</th>
		<th>Update</th>
	</tr>
	{% for team_player in team_players %}
		<tr>
			<th><a href="{% url 'players:player_detail' team_player.player.name %}">{{ team_player.player.name }}</a></th>
			<td>{{ team_player.player.squad }}</td>
			<td>{{ team_player.player.venom }} ml</td>
			<td>{{ team_player.player.category }}</td>
			<td>{{ team_player.player.fresher_pg }}</td>
			<td><a href="{% url 'team:update' team_player.player.name %}">Yes</td>
		</tr>
	{% endfor %}
</ul>
</table>
{% endblock %}

team/templates/team/match.html
{% extends 'home/base.html' %}

{% block title %}
Select Match
{% endblock %}

{% block body %}
<h1 align='center'>Substitutions Left: {{ info }}</h1>
<h1 align='center'>Select Match</h1>
<br/>
<form action="{% url 'team:index' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='300'>
		<tr align='left'>
			<th>
				<label>Match:</label>
			</th>
			<td>
				<select name="match"><!-- 
					<option value='5'>Blitzkrieg v/s Strikers (Freezes @ 8 A.M. on 8th April)</option>
					<option value='6'>Redhawks v/s Musketeers (Freezes @ 1 P.M. on 8th April)</option> -->
				</select>
			</td>
		</tr>
	</table>
	<br/>
	<!-- <input type='submit' value='Select Match'>
 --></form>
{% endblock %}

team/templates/team/player_options.html
{% for p in players %}
<option value="{{ p }}">{{ p }} ({{ p.venom }} ml) {{ p.category }} {{ p.fresher_pg }}</option>
{% endfor %}

team/templates/team/team_create.html
{% extends 'home/base.html' %}

{% block title %}
Create Team
{% endblock %}

{% block body %}
<h1 align='center'>Create Team</h1>
<br/><br/>
<h2 align='center'>Rules</h2>
<br/>
<h4>1. Zeheri Team should consist of atleast 3 Batsmen, 3 Bowler, 1 Wicket-Keeper and 1 All-Rounder</h4>
<h4>2. Overall venom shouldn't exceed 1100 ml</h4>
<h4>3. Atleast 2 UG Freshers and 1 PG student</h4>
<h4>4. 11 Players are to be selected</h4>
<h4>5. 1 Player will be selected as Black Mamba player</h4>
<h4>6. 20 number of substitutions are allowed in the entire league</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;6.1. The number of changes between two freezed teams will be counted as substitutions</h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;6.2. UG Fresher replaced with UG Fresher will not be counted as substitution</h4>
<br/>
<form action="{% url 'team:teamAddIndex' %}" align='center'>
    <input type="submit" value="Generate Team"/>
</form>
{% endblock %}

team/templates/team/team_lists.html
{% extends 'home/base.html' %}

{% block title %}
{{ user.get_full_name }} | Teams
{% endblock %}

{% block body %}
<h1 align='center'>{{ user.get_full_name }} | Teams</h1>
<br/>
<h2 align='center'>Black Mambas</h2>
{% for bm in black_mambas %}
<h4 align='center'>Match {{ forloop.counter }}: {{ bm }}</h4>
{% endfor %}
<br/>
{% for team in teams %}
<h2 align='center'>Match {{ forloop.counter }}</h2>
<br/>
<table border='2' align='center'>
	<col width='300'>
	<col width='150'>
	<col width='100'>
	<col width='100'>
	<col width='100'>
	<tr>
		<th>Name</th>
		<th>Squad</th>
		<th>Venom</th>
		<th>Category</th>
		<th>Fresher/PG</th>
	</tr>
	{% for team_player in team %}
		<tr>
			<th><a href="{% url 'players:player_detail' team_player.player.name %}">{{ team_player.player.name }}</a></th>
			<td>{{ team_player.player.squad }}</td>
			<td>{{ team_player.player.venom }} ml</td>
			<td>{{ team_player.player.category }}</td>
			<td>{{ team_player.player.fresher_pg }}</td>
		</tr>
	{% endfor %}
</ul>
</table>
{% endfor %}
{% endblock %}

team/templates/team/update.html
{% extends 'home/base.html' %}

{% block title %}
Update Player
{% endblock %}

{% block body %}
<h1 align='center'>Update Player</h1>
<br/>
<form action="{% url 'team:playerUpdate' %}" method='post' align='center'>
	{% csrf_token %}
	<table align='center'>
		<col width='150'>
		<col width='350'>
		<tr align='left'>
			<th>
				<label>Squad:</label>
			</th>
			<td>
				<select name="squad" required id="id_squad">
					<option value="">---------</option>
  					{% for s in squads %}
						<option value='{{ s }}'>{{ s }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr align='left'>
			<th>
				<label>Player:</label>
			</th>
			<td>
				<select name="player" required id="id_player">
  					<option value="" selected>---------</option>
				</select>
			</td>
		</tr>
	</table>
	<br/>
	<input type='submit' value='Update Player'>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	$('#id_squad').change(function () {
		var url = "{% url 'team:loadPlayer' %}";
		var squad = $(this).val();

		$.ajax({
			url: url,
			data: {
				'squad' : squad
			},
			success: function (data){
				$('#id_player').html(data);
			}
		});
	});
</script>
{% endblock %}